# these all are random values just to depict the real world scenario 
database:
  ora1:
    password: ora123
  ora2:
    password: ora456
  ora3:
    password: ora789
  pg1:
    password: pg123
  pg2:
    password: pg123
rabbitmq:
  ser1:
    password: rabbitmq123
  ser2:
    password: rabbitmq456
kafka:
  serv1:
    password: kafkad123

